### ISSUE TITLE
[UMBRELLA] patch submission status

### ISSUE THREAD

**Issue by AkihiroSuda** [rootless-containers/usernetes#42]
Kubernetes (https://github.com/rootless-containers/usernetes/tree/master/src/patches/kubernetes)
* [x] KEP: https://github.com/kubernetes/enhancements/pull/1371 (being updated)
* [x] Patches: https://github.com/kubernetes/kubernetes/pull/92863

CRI-O (https://github.com/rootless-containers/usernetes/tree/master/src/patches/crio)
* [x] rootless: enable resource limit when cgroup v2 controllers are delegated: https://github.com/cri-o/cri-o/pull/4528

**Comment by AkihiroSuda** [comment]
submitted PR for non-cgroup stuff: https://github.com/kubernetes/kubernetes/pull/78635

**Comment by AkihiroSuda** [comment]
KEP for "none" cgroup driver: https://github.com/kubernetes/enhancements/pull/1084

**Comment by AkihiroSuda** [comment]
new KEP: https://github.com/kubernetes/enhancements/pull/1371

**Comment by AkihiroSuda** [comment]
The current blocker toward upstreaming the KEP is to get the entire components to work with cgroup (v2) via systemd. `libcontainer/systemd` needs to be updated first.

**Comment by AkihiroSuda** [comment]
The k/k PR was merged: https://github.com/kubernetes/kubernetes/commit/ebbe63f116500b5f3c4fcd1dacbc8d7eb1c7e7a2

We no longer need any patch for cgroup v2, but we still need the [`[Not for Upstream] kubelet: new cgroup driver: "none"`](https://github.com/rootless-containers/usernetes/blob/6bd26a7d8ca7bff70d6dc36ed768c522d29288a8/src/patches/kubernetes/0001-Not-for-Upstream-kubelet-new-cgroup-driver-none.patch) patch for cgroup v1.

The "none" cgroup driver is deprecated and will be removed in a future release of Usernetes.
